version: 2.1

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    # https://circleci.com/docs/2.0/executor-types/
    # https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: 'cimg/openjdk:17.0'
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test